### ISSUE TITLE
Native Android Support

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#1659]
### Problem Statement

.NET 6 includes `net6.0-android` which allows access to Android types through bindings.

When running on this environment, the chances of crashes due to errors outside of the ".NET-land" are significantly increased. We can detect such issues through our [Sentry Android SDK](https://github.com/getsentry/sentry-java). This is how the Sentry's [Flutter](https://github.com/getsentry/sentry-dart) and [React Native](https://github.com/getsentry/sentry-react-native) SDKs work. 

### Tasks

- [x] Introduce `net6.0-android` target
- [x] Introduce bindings to the Sentry Android SDK
- [x] `Sentry.Init` that takes the Android Context and passes it to the Sentry Android SDK
- [x] Hook on `CrashedLastRun` to update session information
- [x] Enable global hub mode (share scope/state globally)
- [x] Set session tracking on by default
- [x] Sample crashes from Kotlin
- [x] Sample crashes from C

The above solved through: #1288

Remaining Tasks:
- [x] Complete diagnostic logger
- [x] Warnings in bindings
- [x] Integration/smoke tests #1662 #1704
- [x] Scope sync.  #1737 
- [x] Pass .NET options down to Android
- [ ] Foreground/Background events to call into Session Pause/Resume
- [x] Bump Android SDK to 6.0.0 and drop Gson as a NuGet dependency
- [x] Bundle a manifest metadata that sets `<meta-data android:name="io.sentry.auto-init" android:value="false" />`
- [ ] Upload native debug symbols through `sentry-cli`
- [ ] Roslyn analyzer to select the right overload 
- [ ] Add [JavaDoc](https://docs.microsoft.com/en-us/xamarin/android/platform/binding-java-library/customizing-bindings/naming-parameters-with-javadoc#integrating-javadoc-html-into-a-java-binding-project) 
- [ ] Build, cache the Android SDK and change its name to `sentry.java.android.dotnet` (see: https://github.com/getsentry/sentry-unity/pull/725)

**Comment by mattjohnsonpint** [comment]
Since we've had Android support in one form or another since 3.18.0, I'm closing this issue.  We can open new issues for individual items as needed.
