### ISSUE TITLE
.NET MAUI Support (Preview 3)

### ISSUE THREAD

**Issue by mattjohnsonpint** [getsentry/sentry-dotnet#1769]
This is a subset of the issue tracking the complete MAUI support (#1174)  and builds upon the work completed for Preview 1 (#1651) and Preview 2 (#1729)

Here is the next set of work planned.  Some of these may be pushed to a Preview 4, depending on how things go.

- [x] Support iOS native crashes: #1282
- [x] Support MacCatalyst native crashes: #1848 
- [x] Connect native iOS SDK options: #1849
- [x] Release Health -> Crash rate based on native crashes
   - [x] Ensure a release value exists OOTB. #1856
   - [x] Ensure `AutoSessionTracking` is `true` by default on mobile ([see code here](https://github.com/getsentry/sentry-dotnet/blob/4c662d79ebe2e939bc26846733af4803013908d5/src/Sentry/SentryOptions.cs#L592-L598))
- [x] Gather device and context info in `IosEventProcessor` #1884
- [x] Consolidate the `Distribution` option from Android and iOS and move into the main SDK. 
- [x] Getting Started Wizard: https://github.com/getsentry/sentry-docs/pull/5271
- [x] ~Platform logo icon (https://github.com/getsentry/platformicons)~ We'll stick the standard .NET logo

**Comment by mattjohnsonpint** [comment]
This was released as part of 3.21.0.
