### ISSUE TITLE
Bundle `sentry-cli` in `Sentry` NuGet package

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#2074]
[Sentry CLI](https://docs.sentry.io/product/cli/) offers many features.
The main features we use during build phase of projects are:

1. [Uploading debug files](https://docs.sentry.io/product/cli/dif/#uploading-files) including [ProGuard on Android](https://docs.sentry.io/product/cli/dif/#proguard-mapping-upload) and [JS Source Maps](https://docs.sentry.io/product/cli/releases/#sentry-cli-sourcemaps)
2. [Creating source bundles](https://docs.sentry.io/product/cli/dif/#creating-source-bundles)
3. Uploading [commit info](https://docs.sentry.io/product/cli/releases/#sentry-cli-commit-integration), to unlock [suspect commits](https://docs.sentry.io/product/issues/suspect-commits/)
4. [Uploading release details](https://docs.sentry.io/product/cli/releases/), to enable features like [Release Health](https://docs.sentry.io/product/releases/health/), resolving [issue by release](https://docs.sentry.io/product/releases/#track-release-health) and "First seeing in Release X".

While many dev ecosystems are used to pull a binary and run via the CLI. In others, build system automation abstracts these. We integrate with many, such as [Gradle](https://github.com/getsentry/sentry-android-gradle-plugin), [Fastlane](https://github.com/getsentry/sentry-fastlane-plugin) and [Webpack](https://github.com/getsentry/sentry-webpack-plugin).

In the current integrations we have a mock server that simulates Sentry and validates things. This helps us integration test things such as symbol upload.

## Goals

- [x] Bundle the different builds of `sentry-cli` in the final `Sentry` NuGet package - #2107
  * Pin the version in a file that can be bumped, triggering download of the newer version.([don't check-in the binary](https://github.com/getsentry/sentry-fastlane-plugin/issues/165))
- [ ] ~[GitHub workflow to automatically open PR](https://github.com/getsentry/github-workflows) with updates for Sentry CLI~
  - (Moved to #2141)
- [x] On Release build, upload debug files: PPDB and native - #2107
- [ ] ~Upload Release info to Sentry~ 
  - (Moved to #2142)
- [x] Gracefully downgrade in case Sentry is offline: https://github.com/getsentry/team-mobile/issues/3
  - Already handled via `SENTRY_ALLOW_FAILURE` env var
- [x] Opt-in to upload on Debug builds (Set `<SentryUploadSymbols>true</SentryUploadSymbols>` in app csproj)
- [ ] ~Opt-in to upload commit info~
  - (Moved to #2143)

Relates to:

* https://github.com/getsentry/team-mobile/issues/33
* https://github.com/getsentry/sentry-dotnet/issues/1850
* https://github.com/getsentry/sentry-dotnet/issues/1740

**Comment by bruno-garcia** [comment]
To make it easier to get the org/proj/auth information to get CLI going, we can use the `wizard` endpoint: 
* https://github.com/getsentry/sentry-dotnet/issues/1850#issuecomment-1363279938
