### ISSUE TITLE
Aspire Sample

### ISSUE THREAD

**Issue by jamescrosswell** [getsentry/sentry-dotnet#3082]
We can [integrate with Aspire via OpenTelemetry](https://learn.microsoft.com/en-us/dotnet/aspire/fundamentals/telemetry#net-aspire-opentelemetry-integration) already. 

Also, we might be able contribute this to https://github.com/dotnet/aspire-samples

We have a [basic sample working](https://github.com/jamescrosswell/aspire-samples/tree/aspire-with-sentry). 

#TODO 

- [x] Code review for the Sample
- [ ] Determine how/where we want to make the sample available
- [ ] Investigate the possibility of a Sentry component for Aspire ([see discussion](https://github.com/dotnet/aspire/discussions/1188))

**Comment by jamescrosswell** [comment]
Sample published here:
- https://github.com/getsentry/sentry-dotnet-aspire-demo
